/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dct.main;

import com.dct.contact.AddContact;
import com.dct.hibernate.ConfigurationFile;
import com.dct.sales.SalesInvoiceMakerIF1;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author Subayan
 */
public class Frame1 extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
        myInit();
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_contact = new javax.swing.JMenu();
        menuItem_addContact = new javax.swing.JMenuItem();
        menu_sales = new javax.swing.JMenu();
        menuItem_salesInvoice = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BMS");

        jDesktopPane1.setToolTipText("Workstation");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        menu_contact.setText("Contacts");

        menuItem_addContact.setText("Add New ...");
        menuItem_addContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_addContactActionPerformed(evt);
            }
        });
        menu_contact.add(menuItem_addContact);

        jMenuBar1.add(menu_contact);

        menu_sales.setText("Sales");

        menuItem_salesInvoice.setText("Inovice");
        menuItem_salesInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_salesInvoiceActionPerformed(evt);
            }
        });
        menu_sales.add(menuItem_salesInvoice);

        jMenuBar1.add(menu_sales);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-888)/2, (screenSize.height-593)/2, 888, 593);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItem_salesInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_salesInvoiceActionPerformed
      JInternalFrame f = new SalesInvoiceMakerIF1(); 
      addToDesktop(f); 
        
    }//GEN-LAST:event_menuItem_salesInvoiceActionPerformed

    private void menuItem_addContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_addContactActionPerformed
      JInternalFrame f = new AddContact(); 
      addToDesktop(f); 
    }//GEN-LAST:event_menuItem_addContactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuItem_addContact;
    private javax.swing.JMenuItem menuItem_salesInvoice;
    private javax.swing.JMenu menu_contact;
    private javax.swing.JMenu menu_sales;
    // End of variables declaration//GEN-END:variables

    public static ConfigurationFile config;
    /**
     * 
     * @param f  Internal frame which is requiered to be added
     */
    
    private void myInit(){
        
     config = new ConfigurationFile();
    }
    private void addToDesktop(JInternalFrame f){
            try {
            jDesktopPane1.add(f);
            f.setSelected(true);    
            f.setVisible(true);
         } catch (PropertyVetoException ex) {
            Logger.getLogger(Frame1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    

}
