/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dct.sales;

import com.dct.support.*;
import com.toedter.calendar.JCalendar;
import java.awt.Component;
import java.awt.EventQueue;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.EventObject;
import javax.swing.DefaultCellEditor;

import javax.swing.text.JTextComponent;
import rawdata.ComboboxData;

/**
 *
 * @author Subayan
 */
public class SalesInvoiceMakerIF1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form SalesInvoiceMakerIF
     */
    public SalesInvoiceMakerIF1() {
        initComponents();
        myInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmb_productList = new javax.swing.JComboBox();
        pop_tableMenu = new javax.swing.JPopupMenu();
        pmenuItem_add = new javax.swing.JMenuItem();
        pmenuItem_delete = new javax.swing.JMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnl_base = new javax.swing.JPanel();
        toll_top = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pnl_partyDetails = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmb_partyName = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA_partyDetails = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_invoiceNo = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        dateChoser = new com.toedter.calendar.JDateChooser();
        pnl_prouctDetails = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){

            @Override // Always selectAll()
            public boolean editCellAt(int row, int column, EventObject e) {

                boolean result = super.editCellAt(row, column, e);
                final Component editor = getEditorComponent();
                if (editor == null || !(editor instanceof JTextComponent)) {
                    return result;
                }
                if (e instanceof MouseEvent) {
                    EventQueue.invokeLater(new Runnable() {

                        @Override
                        public void run() {
                            ((JTextComponent) editor).selectAll();
                        }
                    });
                } else {
                    ((JTextComponent) editor).selectAll();
                }
                return result;
            }

        };
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmb_taxSelect = new javax.swing.JComboBox();

        cmb_productList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ande", "Allu", "Piyaz", "Tamatar", "Bhindi", "Patta Gobi", "Palak", "Muli", "Gajar", "Fool Gobi", "Fali" }));

        pmenuItem_add.setText("Add Row");
        pmenuItem_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmenuItem_addActionPerformed(evt);
            }
        });
        pop_tableMenu.add(pmenuItem_add);

        pmenuItem_delete.setText("Delete Row");
        pop_tableMenu.add(pmenuItem_delete);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Sales Invoice");
        setToolTipText("Register Your sales");

        pnl_base.setAutoscrolls(true);

        toll_top.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        toll_top.setRollover(true);

        jButton1.setText("Save");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toll_top.add(jButton1);

        jButton2.setText("Cancel");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toll_top.add(jButton2);

        pnl_partyDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Party", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.black));

        jLabel1.setText("Party Name");

        cmb_partyName.setMaximumRowCount(12);
        cmb_partyName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Google Inc.", "Facebook Inc.", "Linkdin Corp.", "Bing", "Microsoft", "Infosys", "Genpack", "Hindustan Uniliver", "Hindustan Motors", "General Motors" }));
        cmb_partyName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmb_partyName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_partyNameItemStateChanged(evt);
            }
        });

        jLabel2.setText("Party Details");

        txtA_partyDetails.setBackground(new java.awt.Color(240, 240, 240));
        txtA_partyDetails.setColumns(20);
        txtA_partyDetails.setEditable(false);
        txtA_partyDetails.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        txtA_partyDetails.setLineWrap(true);
        txtA_partyDetails.setRows(5);
        txtA_partyDetails.setWrapStyleWord(true);
        txtA_partyDetails.setFocusable(false);
        jScrollPane1.setViewportView(txtA_partyDetails);

        jLabel3.setText("Invoice No.");

        jLabel4.setText("Date");

        jLabel10.setText("Related Documents");

        lbl_invoiceNo.setText("1");

        jButton3.setText("Add Docs");

        jTextArea2.setBackground(new java.awt.Color(244, 244, 244));
        jTextArea2.setColumns(20);
        jTextArea2.setEditable(false);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setFocusable(false);
        jScrollPane4.setViewportView(jTextArea2);

        dateChoser.setDateFormatString("d MMM, yyyy");

        javax.swing.GroupLayout pnl_partyDetailsLayout = new javax.swing.GroupLayout(pnl_partyDetails);
        pnl_partyDetails.setLayout(pnl_partyDetailsLayout);
        pnl_partyDetailsLayout.setHorizontalGroup(
            pnl_partyDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_partyDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_partyDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_partyDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cmb_partyName, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_partyDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)))
                .addGap(51, 51, 51)
                .addGroup(pnl_partyDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_partyDetailsLayout.createSequentialGroup()
                        .addGroup(pnl_partyDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(pnl_partyDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_partyDetailsLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(lbl_invoiceNo))
                            .addGroup(pnl_partyDetailsLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(dateChoser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(pnl_partyDetailsLayout.createSequentialGroup()
                        .addGroup(pnl_partyDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jButton3))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        pnl_partyDetailsLayout.setVerticalGroup(
            pnl_partyDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_partyDetailsLayout.createSequentialGroup()
                .addGroup(pnl_partyDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmb_partyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(lbl_invoiceNo))
                .addGap(17, 17, 17)
                .addGroup(pnl_partyDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_partyDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnl_partyDetailsLayout.createSequentialGroup()
                        .addGroup(pnl_partyDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(pnl_partyDetailsLayout.createSequentialGroup()
                                .addGroup(pnl_partyDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(dateChoser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_partyDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl_partyDetailsLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3))
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );

        cmb_partyName.setEditable(true);
        cmb_partyName.setSelectedIndex(-1);

        pnl_prouctDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Product Details"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Long(1), null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "S. No.", "Product Name", "Rate", "Tax", "Price", "Quantity", "Discount(%)", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setRowHeight(18);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setMinWidth(50);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
        jTable1.getColumnModel().getColumn(1).setMinWidth(300);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(300);
        jTable1.getColumnModel().getColumn(1).setMaxWidth(300);

        jLabel5.setText("Products");

        jLabel6.setText("Total");

        jLabel7.setText("Tax");

        jLabel8.setText("Grand Total");

        jLabel9.setText("Tax Type");

        cmb_taxSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VAT @ 14%", "VAT @ 5%", "CST @ 2%" }));
        cmb_taxSelect.setSelectedIndex(-1);
        cmb_taxSelect.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnl_prouctDetailsLayout = new javax.swing.GroupLayout(pnl_prouctDetails);
        pnl_prouctDetails.setLayout(pnl_prouctDetailsLayout);
        pnl_prouctDetailsLayout.setHorizontalGroup(
            pnl_prouctDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_prouctDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_prouctDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_prouctDetailsLayout.createSequentialGroup()
                        .addGroup(pnl_prouctDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                            .addGroup(pnl_prouctDetailsLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_prouctDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_taxSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_prouctDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(117, 117, 117))))
        );
        pnl_prouctDetailsLayout.setVerticalGroup(
            pnl_prouctDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_prouctDetailsLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl_prouctDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_prouctDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(pnl_prouctDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(cmb_taxSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_baseLayout = new javax.swing.GroupLayout(pnl_base);
        pnl_base.setLayout(pnl_baseLayout);
        pnl_baseLayout.setHorizontalGroup(
            pnl_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_baseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_partyDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_prouctDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(toll_top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_baseLayout.setVerticalGroup(
            pnl_baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_baseLayout.createSequentialGroup()
                .addComponent(toll_top, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_partyDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_prouctDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 239, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(pnl_base);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {
            pop_tableMenu.show(jTable1, evt.getX(), evt.getY());
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void pmenuItem_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmenuItem_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pmenuItem_addActionPerformed

    private void cmb_partyNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_partyNameItemStateChanged
         txtA_partyDetails.setText(cmb_partyName.getEditor().getItem().toString());
    }//GEN-LAST:event_cmb_partyNameItemStateChanged

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
       
    }//GEN-LAST:event_jTable1KeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmb_partyName;
    private javax.swing.JComboBox cmb_productList;
    private javax.swing.JComboBox cmb_taxSelect;
    private com.toedter.calendar.JDateChooser dateChoser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lbl_invoiceNo;
    private javax.swing.JMenuItem pmenuItem_add;
    private javax.swing.JMenuItem pmenuItem_delete;
    private javax.swing.JPanel pnl_base;
    private javax.swing.JPanel pnl_partyDetails;
    private javax.swing.JPanel pnl_prouctDetails;
    private javax.swing.JPopupMenu pop_tableMenu;
    private javax.swing.JToolBar toll_top;
    private javax.swing.JTextArea txtA_partyDetails;
    // End of variables declaration//GEN-END:variables

    private void myInit() {
        cmb_partyName.setModel(new ComboboxData().getReadyModel());
        getJtableReady();
        lbl_invoiceNo.setText("001");
        dateChoser.setDate(Calendar.getInstance().getTime());
        //lbl_date.setText(new SimpleDateFormat("dd MMM YYYY").format(Calendar.getInstance().getTime()));
    }

    private void getJtableReady() {
        jTable1.getColumnModel().getColumn(1).setCellEditor(new DefaultCellEditor(new ProductCombobox(jTable1)));
        jTable1.getModel().addTableModelListener(new InvoiceTableModelListener());


        cmb_partyName.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {

            @Override
            public void keyReleased(KeyEvent e) {

                String st = cmb_partyName.getEditor().getItem().toString();
                int key = e.getKeyCode();
                if (key == KeyEvent.VK_ENTER) {
                    txtA_partyDetails.setText(cmb_partyName.getEditor().getItem().toString());
                }

                if ((key >= 48 && key <= 57) || (key >= 65 && key <= 96) || (key >= 97 && key <= 122) || (key == 8) || (key == KeyEvent.VK_SPACE)) {
                    cmb_partyName.setModel(new ComboboxData().getFilteredModel(st));
                    if (cmb_partyName.getItemCount() > 0) {
                        cmb_partyName.showPopup();
                        if (key != 8) {
                            ((JTextComponent) cmb_partyName.getEditor().getEditorComponent()).select(st.length(), cmb_partyName.getEditor().getItem().toString().length());
                            // realy long code this is .... :O
                        } else {
                            cmb_partyName.getEditor().setItem(st);
                        }

                    } else {
                        cmb_partyName.addItem(st);
                    }
                }
            }
        });


        //  rate
        jTable1.getColumnModel().getColumn(2).setCellEditor(new CurrencyEditor());
        jTable1.getColumnModel().getColumn(2).setCellRenderer(new CurrencyRenderer());
        
        //  Tax
        jTable1.getColumnModel().getColumn(3).setCellEditor(new CurrencyEditor());
        jTable1.getColumnModel().getColumn(3).setCellRenderer(new PercentageRender());
        
        // price
        jTable1.getColumnModel().getColumn(4).setCellEditor(new CurrencyEditor());
        jTable1.getColumnModel().getColumn(4).setCellRenderer(new CurrencyRenderer());
        // Quantity
        jTable1.getColumnModel().getColumn(5).setCellEditor(new CurrencyEditor());
        jTable1.getColumnModel().getColumn(5).setCellRenderer(new CurrencyRenderer(0, 0));
        // discount
        jTable1.getColumnModel().getColumn(6).setCellEditor(new CurrencyEditor());
        jTable1.getColumnModel().getColumn(6).setCellRenderer(new PercentageRender());
         // Amount
        jTable1.getColumnModel().getColumn(7).setCellEditor(new CurrencyEditor());
        jTable1.getColumnModel().getColumn(7).setCellRenderer(new CurrencyRenderer());

    }
}
